# Generated by Django 4.2.16 on 2025-02-19 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
